name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.4 # Zaktualizowano do najnowszej wersji

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0 # Zaktualizowano do najnowszej wersji
        with:
          node-version: "16" # Zostaw aktualną wersję Node.js, którą używasz

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        working-directory: zakupownik # Ustawienie folderu roboczego na "zakupownik"
